version:  '3.8'
services:
  web:
  build: .
  ports:
    - "5000:5000"
  environment:
    - MONGO_HOST=mongodb
  depends_on:
    - mongodb

mongodb:
  image: mongo
  environment:
    - MONGO_INITDB_ROOT_USERNAME: root
    - MONGO_INITDB_ROOT_PASSWORD: pass
  volumes:
    - mongo-data:/data/db

volumes:
   mongo-data:

        